var str = "Curricular Practical Training (CPT) is off-campus work authorization that allows F-1 students to engage in employment that is an integral part of an established curriculum. Curricular practical training is defined to be alternative work/study, internship, cooperative education, or any other type of required internship or practicum that is offered by sponsoring employers through cooperative agreements with the school.What does this mean?Degree Requirement: a practical experience is required of all students in a degree program to complete their degree. Course Requirement: a practical experience is required as part of a course (like the Stevens practicum course) in which a student will be receiving credit.Thesis/Dissertation Requirement: a practical experience is required for completion of the thesis/dissertation.Co-Op Program: as part of an approved Co-Op programJust having an internship is not a Co-Op experience. Undergraduate Students should reach out to the Career Center for more information about Co-Op programs (Links to an external site.).CPT must be directly related to your field of study. ISSS does not determine if your off-campus work experience is related to your major. Your academic advisor, academic department staff, practicum instructor, Career Center staff, Graduate Academics and Student Success staff, or Undergraduate Academics staff can help you determine if the job opportunity is related to your major field of study. ISSS also does not make decisions in the number of credits you can register for your practicum experience. ISSS only issues the CPT work authorization on the I-20 AFTER you receive academic approval. It is important to remember that your primary objective under the F-1 visa status is to be a student first by taking courses and earning a degree. CPT work authorization is a BENEFIT of F-1 status, and work is not your primary objective under the F-1 visa before completion of your degree. CPT employment MAY NOT delay completion of an academic program. Additionally, if you complete your degree requirements prior to the end date listed on your I-20, you cannot just enroll in the practicum course for CPT work authorization. If you will complete your degree prior to the end date listed on your I-20 (example: complete your degree in 3 semesters instead of 4), your I-20 will be shortened to the semester end date and you will need to apply for OPT to continue working.If you are not making normal academic progress toward your degree program because you are too involved in your off-campus employment and cannot meet your academic obligations, you may not be eligible for a program extension or face other academic consequences. ";

var strarr = str.split(' ');

var tararr = [];

strarr.forEach(element => {
    if(element.length == 10){
        tararr.push(element.toLowerCase());
    }
});

console.log(tararr);